@echo off
echo Starting Transaction Categorization System...
echo.
echo Checking dependencies...
pip install -q -r requirements.txt
echo.
echo Generating sample data...
python sample_data_generator.py
echo.
echo Starting Streamlit application...
streamlit run app.py

